[versions]
loom = "1.13-SNAPSHOT"
yamlang = "1.4.1"
minecraft = "1.21.11"
vineflower = "1.11.1"
fabric-loader = "0.18.2"
fabric-api = "0.139.4+1.21.11"
fabric-yarn = "1.21.11+build.2"

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "loom" }
yamlang = { id = "me.fallenbreath.yamlang", version.ref = "yamlang" }

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
vineflower = { group = "org.vineflower", name = "vineflower", version.ref = "vineflower" }
yarn-mappings = { group = "net.fabricmc", name = "yarn", version.ref = "fabric-yarn" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }

